package com.wangzz.mybatisLearn.bean;

import java.util.Date;

public class GithubCompanyInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column github_company_info.id
     *
     * @mbg.generated Thu Jun 06 10:25:05 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column github_company_info.name
     *
     * @mbg.generated Thu Jun 06 10:25:05 CST 2019
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column github_company_info.code
     *
     * @mbg.generated Thu Jun 06 10:25:05 CST 2019
     */
    private String code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column github_company_info.registrationDay
     *
     * @mbg.generated Thu Jun 06 10:25:05 CST 2019
     */
    private Date registrationday;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column github_company_info.character
     *
     * @mbg.generated Thu Jun 06 10:25:05 CST 2019
     */
    private String character;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column github_company_info.legalRepresentative
     *
     * @mbg.generated Thu Jun 06 10:25:05 CST 2019
     */
    private String legalrepresentative;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column github_company_info.capital
     *
     * @mbg.generated Thu Jun 06 10:25:05 CST 2019
     */
    private Long capital;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column github_company_info.province
     *
     * @mbg.generated Thu Jun 06 10:25:05 CST 2019
     */
    private String province;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column github_company_info.city
     *
     * @mbg.generated Thu Jun 06 10:25:05 CST 2019
     */
    private String city;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column github_company_info.address
     *
     * @mbg.generated Thu Jun 06 10:25:05 CST 2019
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column github_company_info.businessScope
     *
     * @mbg.generated Thu Jun 06 10:25:05 CST 2019
     */
    private String businessscope;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column github_company_info.id
     *
     * @return the value of github_company_info.id
     *
     * @mbg.generated Thu Jun 06 10:25:05 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column github_company_info.id
     *
     * @param id the value for github_company_info.id
     *
     * @mbg.generated Thu Jun 06 10:25:05 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column github_company_info.name
     *
     * @return the value of github_company_info.name
     *
     * @mbg.generated Thu Jun 06 10:25:05 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column github_company_info.name
     *
     * @param name the value for github_company_info.name
     *
     * @mbg.generated Thu Jun 06 10:25:05 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column github_company_info.code
     *
     * @return the value of github_company_info.code
     *
     * @mbg.generated Thu Jun 06 10:25:05 CST 2019
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column github_company_info.code
     *
     * @param code the value for github_company_info.code
     *
     * @mbg.generated Thu Jun 06 10:25:05 CST 2019
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column github_company_info.registrationDay
     *
     * @return the value of github_company_info.registrationDay
     *
     * @mbg.generated Thu Jun 06 10:25:05 CST 2019
     */
    public Date getRegistrationday() {
        return registrationday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column github_company_info.registrationDay
     *
     * @param registrationday the value for github_company_info.registrationDay
     *
     * @mbg.generated Thu Jun 06 10:25:05 CST 2019
     */
    public void setRegistrationday(Date registrationday) {
        this.registrationday = registrationday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column github_company_info.character
     *
     * @return the value of github_company_info.character
     *
     * @mbg.generated Thu Jun 06 10:25:05 CST 2019
     */
    public String getCharacter() {
        return character;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column github_company_info.character
     *
     * @param character the value for github_company_info.character
     *
     * @mbg.generated Thu Jun 06 10:25:05 CST 2019
     */
    public void setCharacter(String character) {
        this.character = character == null ? null : character.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column github_company_info.legalRepresentative
     *
     * @return the value of github_company_info.legalRepresentative
     *
     * @mbg.generated Thu Jun 06 10:25:05 CST 2019
     */
    public String getLegalrepresentative() {
        return legalrepresentative;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column github_company_info.legalRepresentative
     *
     * @param legalrepresentative the value for github_company_info.legalRepresentative
     *
     * @mbg.generated Thu Jun 06 10:25:05 CST 2019
     */
    public void setLegalrepresentative(String legalrepresentative) {
        this.legalrepresentative = legalrepresentative == null ? null : legalrepresentative.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column github_company_info.capital
     *
     * @return the value of github_company_info.capital
     *
     * @mbg.generated Thu Jun 06 10:25:05 CST 2019
     */
    public Long getCapital() {
        return capital;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column github_company_info.capital
     *
     * @param capital the value for github_company_info.capital
     *
     * @mbg.generated Thu Jun 06 10:25:05 CST 2019
     */
    public void setCapital(Long capital) {
        this.capital = capital;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column github_company_info.province
     *
     * @return the value of github_company_info.province
     *
     * @mbg.generated Thu Jun 06 10:25:05 CST 2019
     */
    public String getProvince() {
        return province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column github_company_info.province
     *
     * @param province the value for github_company_info.province
     *
     * @mbg.generated Thu Jun 06 10:25:05 CST 2019
     */
    public void setProvince(String province) {
        this.province = province == null ? null : province.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column github_company_info.city
     *
     * @return the value of github_company_info.city
     *
     * @mbg.generated Thu Jun 06 10:25:05 CST 2019
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column github_company_info.city
     *
     * @param city the value for github_company_info.city
     *
     * @mbg.generated Thu Jun 06 10:25:05 CST 2019
     */
    public void setCity(String city) {
        this.city = city == null ? null : city.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column github_company_info.address
     *
     * @return the value of github_company_info.address
     *
     * @mbg.generated Thu Jun 06 10:25:05 CST 2019
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column github_company_info.address
     *
     * @param address the value for github_company_info.address
     *
     * @mbg.generated Thu Jun 06 10:25:05 CST 2019
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column github_company_info.businessScope
     *
     * @return the value of github_company_info.businessScope
     *
     * @mbg.generated Thu Jun 06 10:25:05 CST 2019
     */
    public String getBusinessscope() {
        return businessscope;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column github_company_info.businessScope
     *
     * @param businessscope the value for github_company_info.businessScope
     *
     * @mbg.generated Thu Jun 06 10:25:05 CST 2019
     */
    public void setBusinessscope(String businessscope) {
        this.businessscope = businessscope == null ? null : businessscope.trim();
    }
}